build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.3
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                       command: './bin/phpunit --coverage-clover=coverage.xml'
                       coverage:
                           file: 'coverage.xml'
                           format: 'php-clover'
        php73:
            environment:
                php:
                    version: 7.3
        php74:
            environment:
                php:
                    version: 7.4
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }
